---
title: "6. Web Scraping"
order: 6
---

## Tutorials

1. [Introduction to Web Scraping](scraping-1.qmd)
2. [More Scraping + actionability](scraping-2.qmd)
3. [Playwright + Argparse + Streamlit to create useful apps](scraping-3.qmd)

## Lectures

### Wednesday April 1, 2026

Introduction to web scraping

<iframe id="kmsembed-1_iea5aigr" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_iea5aigr/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 4-1-26"></iframe>

### Monday April 6, 2026

More scraping + actionability

<iframe id="kmsembed-1_r06v23on" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_r06v23on/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 4-6-26"></iframe>


### Wednesday April 8, 2026

Using locators; playwright + Streamlit

<iframe id="kmsembed-1_e4bdwwp9" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_e4bdwwp9/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 4-8-26"></iframe>
