---
title: "IST 356: Programming Techniques for Data Analytics"
subtitle: "Syracuse University, Spring 2026"
toc: true
---

## Course info

**Room:** Hinds Hall 010

**Time:** M/W 2:15PM - 3:35PM

**Instructor:** Collin Capano

**Email:** cdcapano@syr.edu

**Office hours:** M/W 3:40PM - 4:40PM (immediately after class) in Hinds Hall 323G, or by appointment.

**[Syllabus](syllabus.qmd)**


## Class Schedule

*Note:* schedule subject to change as we progress through the semester.

| Week | Dates | Topic |
|----|--------------|----------------------|
| 1  | 1/12, 1/14   | Intro; CLI and Conda |
| 2  | 1/21         | Git & GitHub         |
| 3  | 1/26, 1/28   | Python review - 1    |
| 4  | 2/2, 2/4     | Python review - 2    |
| 5  | 2/9, 2/11    | Writing scripts with Argparse; Streamlit |
| 6  | 2/16, 2/18   | Data wrangling - 1 |
| 7  | 2/23, 2/25   | Data wrangling - 2 |
| 8  | 3/2, 3/4     | Review (3/2) and Mid-term Exam (3/4) |
| -- | 3/8 - 3/15   | Spring Break |
| 9  | 3/16, 3/18   | Web APIs - 1 |
| 10 | 3/23, 3/25   | Web APIs - 2 |
| 11 | 3/30, 4/1    | Web scraping - 1 |
| 12 | 4/6, 4/8     | Web scraping - 2 |
| 13 | 4/13, 4/15   | Data visualization - 1 |
| 14 | 4/20, 4/22   | Data visualization - 2; Review for Final Exam |
| 15 | 4/27         | Final Exam |
| 16 | 5/4          | Project due |

## Important dates

| Date        | |
|-------------|---------------------------------------------------|
| Mon. 1/12   | First day of class |
| Mon. 1/19   | Martin Luther King, Jr. Day: **No class** |
| Mon. 2/2    | Academic/Financial drop deadline; Religious observance notification deadline |
| 3/8 - 3/15  | Spring break - **No class** |
| Tues. 4/14  | Withdrawal deadline |
| Mon. 4/27   | Last day of class |
