---
title: "Lectures"
toc: True
---

A list of all the lecture recordings. These are also linked on the unit splash pages.

### Wednesday, January 14, 2026

Introduction to command line interface (CLI)

<iframe id="kmsembed-1_9y785gka" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_9y785gka/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 1-14-26"></iframe>

### Wednesday, January 21, 2026

Contiuation of CLI: bash variables, scripts, and environments. Introduction to Conda.

<iframe id="kmsembed-1_uvpcm86t" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_uvpcm86t/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 1-21-26"></iframe>

### Monday, January 26, 2026

Introduction to Git and GitHub; how to use GitHub Classroom.

<iframe id="kmsembed-1_pmqsjrrv" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_pmqsjrrv/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 1-26-26"></iframe>

### Wednesday, January 28, 2026

Overview of assignment 1. Introduction to Python: input, output, variables, types, conditionals.

<iframe id="kmsembed-1_i76mpcln" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_i76mpcln/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 1-28-26"></iframe>

### Monday, February 2, 2026

Python lists and dictionaries; definite and indefinite loops. (Pre-recorded lecture.)

<iframe id="kmsembed-1_gkvfe747" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_gkvfe747/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 2-2-26"></iframe>

### Wednesday, February 4, 2026

Python functions; string operations; file I/O. (Pre-recorded lecture.)

<iframe id="kmsembed-1_f1uqv8ts" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_f1uqv8ts/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 2-4-26"></iframe>

### Monday, February 9, 2026

Python classes; imports

<iframe id="kmsembed-1_d560o5wj" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_d560o5wj/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 2-9-26"></iframe>

### Wednesday, February 11, 2026

Introduction to Streamlit

<iframe id="kmsembed-1_u3110pjn" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_u3110pjn/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 2-11-26"></iframe>

### Monday, February 16, 2026

Adding command-line options to Python scripts using Argparse

<iframe id="kmsembed-1_3opf3u4e" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_3opf3u4e/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 2-16-26"></iframe>

### Wednesday, February 18, 2026

Numpy; intro to Pandas Series

<iframe id="kmsembed-1_iqi4wasr" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_iqi4wasr/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 2-18-26"></iframe>

### Monday, February 23, 2026

Intro to Pandas DataFrame

<iframe id="kmsembed-1_fnn9ggpl" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_fnn9ggpl/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 2-23-26"></iframe>

### Wednesday, February 25, 2026

Combining DataFrames with concat and merge

<iframe id="kmsembed-1_ammg6hcx" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_ammg6hcx/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 2-25-26"></iframe>

### Monday, March 16, 2026

Cleaning data and applying funcitons with Pandas

<iframe id="kmsembed-1_9g40k65r" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_9g40k65r/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 3-16-26"></iframe>

### Wednesday, March 18, 2026

Grouping data and creating pivot tables with Pandas

<iframe id="kmsembed-1_gtx9nyph" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_gtx9nyph/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 3-18-26"></iframe>

### Monday March 23, 2026

Introduction to Web APIs: using GET and the CENT IoT API

<iframe id="kmsembed-1_159sjbsr" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_159sjbsr/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 3-23-26"></iframe>

### Wednesday March 25, 2026

Web APIs: using PUT and caching

<iframe id="kmsembed-1_nwegzhjr" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_nwegzhjr/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 3-25-26"></iframe>

### Monday March 30, 2026

Creating your own API with FastAPI

<iframe id="kmsembed-1_67u7bf50" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_67u7bf50/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 3-30-26"></iframe>

### Wednesday April 1, 2026

Introduction to web scraping

<iframe id="kmsembed-1_iea5aigr" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_iea5aigr/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 4-1-26"></iframe>

### Monday April 6, 2026

More scraping + actionability

<iframe id="kmsembed-1_r06v23on" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_r06v23on/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 4-6-26"></iframe>

### Wednesday April 8, 2026

Using locators; playwright + Streamlit

<iframe id="kmsembed-1_e4bdwwp9" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_e4bdwwp9/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 4-8-26"></iframe>

### Monday April 13, 2026

Visualization 1: intro to matplotlib and Seaborn
<iframe id="kmsembed-1_zeykmj3t" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_zeykmj3t/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 4-13-26"></iframe>

### Wednesday April 15, 2026

Visualization 2: more Seaborn plots; KDE; saving plots

<iframe id="kmsembed-1_yfp4y3ys" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_yfp4y3ys/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 4-15-26"></iframe>

### Monday April 22, 2026

Visualization 3: Creating visualizations with maps

<iframe id="kmsembed-1_d5yxr996" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_d5yxr996/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 4-22-26"></iframe>
