---
title: "2. Python review"
order: 2
---

In this unit we will review some basics of Python programming. You will have covered the material here in IST 256.

## Tutorials

1. [Input, output, variables, types, conditionals](python-1.qmd)
2. [Iterations, lists, dictionaries, comprehensions](python-2.qmd)
3. [Functions, documentation, strings, files](python-3.qmd)
4. [Classes](python-4.qmd)
5. [Modules and testing](python-5.qmd)

## Lectures

### Wednesday, January 28, 2026

Overview of assignment 1. Introduction to Python: input, output, variables, types, conditionals.

<iframe id="kmsembed-1_i76mpcln" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_i76mpcln/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 1-28-26"></iframe>

### Monday, February 2, 2026

Python lists and dictionaries; definite and indefinite loops. (Pre-recorded lecture.)

<iframe id="kmsembed-1_gkvfe747" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_gkvfe747/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 2-2-26"></iframe>

### Wednesday, February 4, 2026

Python functions; string operations; file I/O. (Pre-recorded lecture.)

<iframe id="kmsembed-1_f1uqv8ts" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_f1uqv8ts/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 2-4-26"></iframe>

### Monday, February 9, 2026

Python classes; imports

<iframe id="kmsembed-1_d560o5wj" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_d560o5wj/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 2-9-26"></iframe>
