---
title: "7. Visualization"
order: 7
---

## Tutorials

1. [Introduction to maptlotlib and seaborn](visualization-1.qmd) 
2. [More Seaborn plots](visualization-2.qmd)
3. [Saving plots and displaying in Streamlit](visualization-3.qmd)
4. [Creating visualizations with maps](visualization-4.qmd)

## Lectures

### Monday April 13, 2026

Visualization 1: intro to matplotlib and Seaborn
<iframe id="kmsembed-1_zeykmj3t" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_zeykmj3t/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 4-13-26"></iframe>

### Wednesday April 15, 2026

Visualization 2: more Seaborn plots; KDE; saving plots

<iframe id="kmsembed-1_yfp4y3ys" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_yfp4y3ys/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 4-15-26"></iframe>

### Monday April 22, 2026

Visualization 3: Creating visualizations with maps

<iframe id="kmsembed-1_d5yxr996" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_d5yxr996/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 4-22-26"></iframe>
