---
title: "4. Data Wrangling"
order: 4
---

In this unit we will learn about how to easily manage and manipulate data in Python using NumPy and Pandas.

## Tutorials

1. [Introduction to NumPy](numpy_basics.qmd)
2. [Introduction to Pandas: Series and DataFrames](pandas-1.qmd)
3. [Data I/O with Pandas](pandas-2.qmd)
4. [Joining Multiple Pandas Dataframes](pandas-3.qmd)
5. [Basic data cleaning with Pandas](pandas-4.qmd)

## Lectures


### Wednesday, February 18, 2026

Numpy; intro to Pandas Series

<iframe id="kmsembed-1_iqi4wasr" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_iqi4wasr/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 2-18-26"></iframe>

### Monday, February 23, 2026

Intro to Pandas DataFrame

<iframe id="kmsembed-1_fnn9ggpl" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_fnn9ggpl/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 2-23-26"></iframe>

### Wednesday, February 25, 2026

Combining DataFrames with concat and merge

<iframe id="kmsembed-1_ammg6hcx" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_ammg6hcx/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 2-25-26"></iframe>

### Monday, March 16, 2026

Cleaning data and applying funcitons with Pandas

<iframe id="kmsembed-1_9g40k65r" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_9g40k65r/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 3-16-26"></iframe>

### Wednesday, March 18, 2026

Grouping data and creating pivot tables with Pandas

<iframe id="kmsembed-1_gtx9nyph" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_gtx9nyph/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 3-18-26"></iframe>
