---
title: "Introduction and computer setup"
subtitle: "IST 356 - M003, Syracuse University, Spring 2026"
toc: true
order: 1
---

# Setting up Your Computer and Yourself!

In IST356 we teach you programming for data analytics using the tools and techiques used by those in the industry. As such, you will learn how to setup and configure development environments, use git and github and learn to systematically test your code.

This is unlike IST256 where the emphasis is on the programming basics and the motivations behind learning computational thinking.


|| IST356 | IST256|
|-----|-----|-----|
Programming Environment | Install vscode + git + python on your computer | Web-hosted jupyterhub |
Assignment Submissions | Student learn and use git / github | Built-in assignment submission
Coursework, slides, examples | You clone / diff the prof repo | Autodiff and merge at login

In this course you'll do it the real way, nothing is hidden / abstracted away for you.

## Step 1: Software Installs

Here's what you'll need to install on your computer. Please read this entire section prior to installing. :-)

1.  **Visual Studio Code**: https://code.visualstudio.com/Download   
    This is a free editor with testing and debugging capabilities. As you install you can accept all defaults, except the last one: DO NOT launch the application when complete! If you do, simply close it. 

2.  **Git Source Code Manager**: https://git-scm.com/download/  
    As you set it up, you will be asked several questions, for which the default selection is fine. EXCEPTION: choose Visual Studio Code as the default editor.

    ::: {.callout-warning}
    **Mac users**: you'll see multiple options for downloading Git Source Code Manager. I recommend using the Xcode version. Clicking on that link will redirect you to the Apple store; from there you will download and install Xcode.
    :::

 

3.  [Miniconda](https://www.anaconda.com/docs/getting-started/miniconda/install#quickstart-install-instructions) 
    **Do not install this yet!** You will install this using the terminal in VSCode after VSCode and Git are installed and setup; see instructions below.

## Step 2: Github Account

Being an SU student comes with some perks. One of them is a Github for Education account and accompanying "backpack" of goodies. To use this benefit, your github account must be associated with your **@syr.edu** email.

### IF YOU HAVE A GITHUB ACCOUNT:

Associate your current account with SU, by adding your email:

1. Go to to https://github.com  and click Sign In 
2. Once you have logged in, go to: https://github.com/settings/emails  
3. Add and verify your SU email address.

### IF YOU DO NOT HAVE A GITHUB ACCOUNT:

You'll need to create an account:

1. Go to to https://github.com  and click Sign In 
2. Follow the on-screen instructions to sign up for an account.
3. Make sure to use your **@syr.edu** email for the account.
4. Add your personal email when you're at it so you don't lose Github access after you graduate!

### Backpack Access

1. Go to the Github Backpack site:  https://education.github.com/pack  
and click **Sign Up For Student Developer Pack**
2. Once your account is verified, you will have backpack access.
3. You'll know its active when you check your billing plan: https://github.com/settings/billing/summary   
you should see a credit here.
4. Once you have backpack access, you can enable Github Copilot AI. https://github.com/settings/copilot 


## Step 3: Configure VS Code

The last step is to configure VS Code for Python debugging. Provided everything else is in order, this should be straightforward.

1.  Open Visual studio code. You will be asked to configure it.
    1.  Set up GitHub Copilot. To do so, you'll need to sign into GitHub by clicking "Continue with GitHub". After you do, you may be dropped into a "Welcome" tab in VS Code. If so, click the "Walkthrough: Setup VS Code" tab to continue set up.
    1.  Pick a theme: Light, Dark, etc...
    1. Add the following Extensions: Python, Jupyter.
    1. **Windows users only**: we'll occasionally be using `bash` in the terminal mode of VSCode. Mac and Linux users have `bash` natively installed in the operating system. Windows users will have gotten a copy of bash when they downloaded and installed Git SCM. However, you need to tell VSCode to use `bash` in the Terminal rather than Windows PowerShell. To do that:
        a.  Click "Unlock productivity with the Command Palette" in the Walthrough tab, then "Open Command Palette". Alternatively, if you don't see that option, open the Command Palette by typing CTRL + SHIFT + P. (Mac users type COMMAND + SHIFT + P).
        b.  Type "Select Default Profile" then hit ENTER.
        c.  Select "Git Bash" from the drop-down options.
        d.  Check that it worked by opening a new terminal: in the file menu, click "Terminal" -> "New Terminal". You should see "bash" in the upper right of the terminal screen.

    1.  Close the welcome Tab but keep VS Code open.

## Step 4: Install Miniconda

### Mac/Linux/Windows Subsystem for Linux (WSL)

1.  Open a terminal in VS Code by clicking "Terminal" -> "New Terminal".

1.  In the terminal window, type:

    ```bash
    cd
    ```

    Then hit ENTER.

1.  Follow the instructions [Quickstart install instructions](https://www.anaconda.com/docs/getting-started/miniconda/install#quickstart-install-instructions) on the Miniconda website. For WSL, select "Linux".

### Windows

1.  Download the [Miniconda installer for Windows](https://www.anaconda.com/download/success). **Click the Downlad button under "Miniconda Installers", *not* the one under "Distribution Installers".**
1.  Run the installer by double-clicking on the downloaded file and follow the steps below.

    -   Click “Run”.
    -   Click on “Next”.
    -   Click on “I agree”.
    -   Select “Just me” and click on “Next”.
    -   Click "Next" to install to the default destination folder.
        
        ::: {.callout-warning}
        If you had tried to install miniconda previously, you may get an error that says "Directory ...\miniconda3 is not empty, please choose a different location." **Do not choose a different location.** Instead, click "OK", then rename the previous miniconda3 directory. You can do that by going to VS Code, opening a new terminal window (click "Terminal" -> "New Terminal"), and entering the following (hit ENTER after each line):

        ```bash
        cd
        mv miniconda3 miniconda3-old
        ```

        Then go back to the Miniconda installer and click "Next".
        :::

    -   Check the option for “Add Anaconda to my PATH environment variable” and check the option for “Register Anaconda as my default Python 3.x”.
        - Note that even though the installation is for Miniconda, the installer uses the word Anaconda in these options.
        - You will also see a message in red text that selecting “Add Anaconda to my PATH environment variable” is not recommended; continue with this selection to make using conda easier in Git Bash. If you have questions or concerns, please contact your instructor.
    -   Click on “Install”.
    -   When the install is complete, Click on “Next”.
    -   Click on “Finish”.

1.  Open a new terminal window in VS Code by clicking "Terminal" -> "New Terminal".

1.  Type the following command to initialize conda:

    ```bash
    conda init bash
    ```

1.  Open a new terminal window in VS Code by either hitting the "+" key next to "bash" in the upper left of the terminal window, or by cliking "Terminal" -> "New Terminal". If conda installed successfullly, you should see `(base)` appear next to or above your command prompt.

## Step 5: Create a conda environment and test it in VS Code

1.  In the bash terminal window in VS Code (make sure it says `(base)` to the left of or above the prompt), type:

    ```bash
    conda create -n ist356 -c conda-forge -y python=3.11 ipykernel
    ```

    Then hit ENTER.

    ::: {.callout-warning}
    The first time you run conda, you may get an error about Terms of Service not being accepted for certain channels. Accept the TOS for those channels by running the commands listed. For example, if one of the channels is `https://repo.anaconda.com/pkgs/main`, copy and paste the command into the terminal:

    ```bash
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
    ```

    Followed by hitting ENTER (to execute a command in the terminal, you hit ENTER after typing/pasting it in). You'll need to do this for each of the channels listed.

    Once you have accepted the TOS for all the channels, run the `conda create` command above again.
    :::


1.  Check to ensure your environment works:
    1.  Click File -> "New File..."
    1.  In the drop down menu, select "Jupyter Notebook".
    1.  Click "Select Kernel" on the right then type "ist356".
    1.  In the first cell, type:

        ```python
        print("hello world!")
        ```

    1.  Hit the run button on the left or type SHIFT + ENTER to execute the code. You should get back "hello world!".
    1.  Close the ipynb file (you may optionally save it; if you do, be sure to call it something other then "Untitled.ipynb", maybe "hello.ipynb" instead).
