---
title: "1. Command line interface and Environments"
order: 1
---

In this unit, you will learn how to use the bash shell in a command line interface (CLI), programming environments, and how to use `conda` to manage environments and install packages.

## Tutorials

1. [Introduction to CLI](shell-intro.qmd)

1. [Environments and Conda](conda.qmd)

## Lecture

### Wednesday, January 14, 2026

Introduction to command line interface (CLI)

<iframe id="kmsembed-1_9y785gka" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_9y785gka/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 1-14-26"></iframe>

### Wednesday, January 21, 2026

Contiuation of CLI: bash variables, scripts, and environments. Introduction to Conda.

<iframe id="kmsembed-1_uvpcm86t" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_uvpcm86t/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 1-21-26"></iframe>
