---
title: "Final Project"
order: 8
---

**Total points:** 24

**Project titles and partners due: April 15**

- Please email me the title of your project and who you will be working with by Wednesday, April 15.

**Due date: May 4**

- This is a hard deadline: nothing will be accepted after that date.

## Partners

You make work on your own or with one other partner. If you work with a partner, you will turn in the project using the same GiHut repository and both of you will receive the same grade.

I will email you GitHub links for the final project once the partners/individuals are established.

## Project Expectations

For the project you can do anything you want, provided it uses what we learned in the course. Here's a summary of what's expected:

1. Python functions in modules with tests

2. Either a Streamlit app or a set of command-line executables (that use argparse) for user interface.

3. Pandas for data manipulation

4. Visualizations

5. APIs (cent.ischool-iot.net portal or any other API's of your choosing) and/or  
Web Scraping using playwright if you cannot find an API.

Your grade is proportional to the number of expectations you complete with intentionality.

## What Type of Project Should I Do?

Its up to you! Do you need some ideas? Consider building a data pipeline like we did in assignment 04/05/06 and then building a dashboard around the data using visualizations and streamlit.

Break your pipeline up into separate python programs to perform each step similar to assignment 05 and 06.


1. Extract data from API's / web scraping / or a dataset. Save the data to a file in your cache folder.

2. Transform the data into a format that is useful for your dashboard. Save the data to a file in your cache folder.

3. Load the data into a pandas and interact with it using streamlit and charts, graphs or maps.

4. part of your extract or transform steps you might need to write functions. Make sure you write tests for these functions, similar to what has been demonstrated in the class assignments.


## I need more inspiration...

Here's a place where you can find API's that might interest you:

- Awesome Public API's: https://github.com/public-apis/public-apis
- US Government API's: https://api.data.gov/
- Portal of Public APIs: https://publicapis.dev/
- Always welcome to use: https://cent.ischool-iot.net/


Here's a suggestion for data sources / datasets of interest:

- SU Library: https://researchguides.library.syr.edu/az/databases?t=8828
- Data Catalog: https://data.world/datasets/free
- Most cities have an open data portal, for example: https://opendata.cityofnewyork.us/
- British Film Institute: https://www.bfi.org.uk/industry-data-insights
- NASA Data, for example: https://www.earthdata.nasa.gov/
- Sports Data: https://www.sports-reference.com/
- US Government data: https://data.gov/
- Google Dataset Search: https://datasetsearch.research.google.com/
- Kaggle Datasets: https://www.kaggle.com/datasets
- Awesome Public Datasets: https://github.com/smuthubabu/awesome-public-datasets


## What are you turning in?

You will be pushing a GitHub repository with your project in it (I will circulate a GitHub repo through GitHub classroom for you to submit your project in).

## In summary

It is important to me that I see "YOU" in your project. That means:

- Share what you learned,
- Do something that interests you,
- Explain what you did and how it works!
